/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    App3Dict: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "address payable",
              name: "initialOwner",
              type: "address",
            },
            {
              internalType: "contract ERC20",
              name: "baseTokenToSet",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "lister",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "wasApproved",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isApproved",
              type: "bool",
            },
          ],
          name: "ApprovedListerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IERC20",
              name: "oldBaseToken",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IERC20",
              name: "newBaseToken",
              type: "address",
            },
          ],
          name: "BaseTokenChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "paidTo",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
          ],
          name: "BaseTokensPayout",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "DefaultMaxQuestionBidChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint24",
              name: "oldValue",
              type: "uint24",
            },
            {
              indexed: false,
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "DefaultSponsorFractionOfOptionPoolChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "tokenContract",
              type: "address",
            },
          ],
          name: "ERC20Withdrawal",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
          ],
          name: "EthWithdrawal",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "GameSponsorMinChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bool",
              name: "oldValue",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "OpenToAnyListerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "donor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPublicGoodsPoolUnpaidBalance",
              type: "uint256",
            },
          ],
          name: "PublicGoodsPoolDonationReceived",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "paidTo",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newTotalPaidOut",
              type: "uint256",
            },
          ],
          name: "PublicGoodsPoolPayout",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "QuestionSponsorMinChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint24",
              name: "oldValue",
              type: "uint24",
            },
            {
              indexed: false,
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "SponsorFractionOfQuestionPoolChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "donor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TipReceived",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "approvedListers",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "baseToken",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "lister",
              type: "address",
            },
            {
              internalType: "bool",
              name: "shouldBeApproved",
              type: "bool",
            },
          ],
          name: "changeApprovedLister",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract ERC20",
              name: "newBaseToken",
              type: "address",
            },
          ],
          name: "changeBaseToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeDefaultMaxQuestionBid",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "changeDefaultSponsorFractionOfOptionPool",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeGameSponsorMin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "changeOpenToAnyLister",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeQuestionSponsorMin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "changeSponsorFractionOfQuestionPool",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultMaxQuestionBid",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultSponsorFractionOfOptionPool",
          outputs: [
            {
              internalType: "uint24",
              name: "",
              type: "uint24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "donateToPublicGoods",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "gameSponsorMin",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "potentialLister",
              type: "address",
            },
          ],
          name: "isAllowedToList",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "openToAnyLister",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "payTo",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "payAmount",
              type: "uint256",
            },
          ],
          name: "payoutBaseTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "recipient",
              type: "address",
            },
          ],
          name: "payoutEth",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "payTo",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "payAmount",
              type: "uint256",
            },
          ],
          name: "payoutPublicGoods",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "publicGoodsPoolPaidOut",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "publicGoodsPoolUnpaidBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "questionSponsorMin",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "sponsorFractionOfQuestionPool",
          outputs: [
            {
              internalType: "uint24",
              name: "",
              type: "uint24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "tip",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          name: "withdrawERC20Tokens",
          outputs: [],
          stateMutability: "pure",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {
        owner: "contracts/PayableOwnable.sol",
        payoutEth: "contracts/PayableOwnable.sol",
        renounceOwnership: "contracts/PayableOwnable.sol",
        transferOwnership: "contracts/PayableOwnable.sol",
        withdrawERC20Tokens: "contracts/PayableOwnable.sol",
        baseToken: "contracts/IGamesController.sol",
        defaultMaxQuestionBid: "contracts/IGamesController.sol",
        defaultSponsorFractionOfOptionPool: "contracts/IGamesController.sol",
        isAllowedToList: "contracts/IGamesController.sol",
      },
    },
    Games: {
      address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      abi: [
        {
          inputs: [
            {
              internalType: "address payable",
              name: "initialOwner",
              type: "address",
            },
            {
              internalType: "contract IGamesController",
              name: "initialController",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "attempter",
              type: "address",
            },
          ],
          name: "PropertyChangeAttemptByNonLister",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "asker",
              type: "address",
            },
            {
              indexed: false,
              internalType: "int8",
              name: "oldValue",
              type: "int8",
            },
            {
              indexed: false,
              internalType: "int8",
              name: "newValue",
              type: "int8",
            },
          ],
          name: "AskerApprovalChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "oldValue",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "CheckInRequiredChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "CheckInStartChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IGamesController",
              name: "oldValue",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IGamesController",
              name: "newValue",
              type: "address",
            },
          ],
          name: "ControllerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "lister",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "newId",
              type: "uint256",
            },
          ],
          name: "Creation",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldValue",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "Descr500Changed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "tokenContract",
              type: "address",
            },
          ],
          name: "ERC20Withdrawal",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "EndTimeChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaidOut",
              type: "uint256",
            },
          ],
          name: "EthWithdrawal",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldValue",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "EventURIChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "oldValue",
              type: "address",
            },
            {
              indexed: false,
              internalType: "contract IERC20",
              name: "newValue",
              type: "address",
            },
          ],
          name: "GameTokenChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldValue",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "ImageURIChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "ListEndChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "ListStartChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "oldValue",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newValue",
              type: "address",
            },
          ],
          name: "ListerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "LocationIDChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "MaxQuestionBidChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "oldValue",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "OpenToAnyAskerChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "referee",
              type: "address",
            },
          ],
          name: "RefereeAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "referee",
              type: "address",
            },
          ],
          name: "RefereeRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint24",
              name: "oldValue",
              type: "uint24",
            },
            {
              indexed: false,
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "SponsorFractionOfOptionPoolChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sponsor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountAdded",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalSponsorshipFromThisSponsor",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalSponsoredAmount",
              type: "uint256",
            },
          ],
          name: "SponsorshipAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldValue",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "Title140Changed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referee",
              type: "address",
            },
          ],
          name: "addReferee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amountToAdd",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "sponsor",
              type: "address",
            },
          ],
          name: "addSponsorship",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "asker",
              type: "address",
            },
            {
              internalType: "int8",
              name: "newValue",
              type: "int8",
            },
          ],
          name: "changeAskerApproval",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "changeCheckInRequired",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeCheckInStart",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IGamesController",
              name: "newController",
              type: "address",
            },
          ],
          name: "changeController",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "changeDescr500",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeEndTime",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "changeEventURI",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "changeImageURI",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeListEnd",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeListStart",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "newValue",
              type: "address",
            },
          ],
          name: "changeLister",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeLocationID",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "changeMaxQuestionBid",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "newValue",
              type: "bool",
            },
          ],
          name: "changeOpenToAnyAsker",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "uint24",
              name: "newValue",
              type: "uint24",
            },
          ],
          name: "changeSponsorFractionOfOptionPool",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "newValue",
              type: "string",
            },
          ],
          name: "changeTitle140",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "lister",
              type: "address",
            },
          ],
          name: "create",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "gameID",
              type: "uint256",
            },
          ],
          name: "gameToken",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "gameID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "potentialLister",
              type: "address",
            },
          ],
          name: "isAllowedToList",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "gameID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "potentialReferee",
              type: "address",
            },
          ],
          name: "isRefereeFor",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "gameID",
              type: "uint256",
            },
          ],
          name: "maxQuestionBid",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "recipient",
              type: "address",
            },
          ],
          name: "payoutEth",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "rowID",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referee",
              type: "address",
            },
          ],
          name: "removeReferee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "gameID",
              type: "uint256",
            },
          ],
          name: "sponsorFractionOfOptionPool",
          outputs: [
            {
              internalType: "uint24",
              name: "",
              type: "uint24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "payAmount",
              type: "uint256",
            },
            {
              internalType: "contract IERC20",
              name: "tokenContract",
              type: "address",
            },
          ],
          name: "withdrawERC20Tokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {
        owner: "contracts/PayableOwnable.sol",
        payoutEth: "contracts/PayableOwnable.sol",
        renounceOwnership: "contracts/PayableOwnable.sol",
        transferOwnership: "contracts/PayableOwnable.sol",
        withdrawERC20Tokens: "contracts/PayableOwnable.sol",
        gameToken: "contracts/IQuestionsController.sol",
        isAllowedToList: "contracts/IQuestionsController.sol",
        isRefereeFor: "contracts/IQuestionsController.sol",
        maxQuestionBid: "contracts/IQuestionsController.sol",
        sponsorFractionOfOptionPool: "contracts/IQuestionsController.sol",
      },
    },
    USDME: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOwner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ECDSAInvalidSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "ERC2612ExpiredSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "ERC2612InvalidSigner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "currentNonce",
              type: "uint256",
            },
          ],
          name: "InvalidAccountNonce",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidShortString",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "str",
              type: "string",
            },
          ],
          name: "StringTooLong",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [],
          name: "EIP712DomainChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "eip712Domain",
          outputs: [
            {
              internalType: "bytes1",
              name: "fields",
              type: "bytes1",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "version",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "chainId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "verifyingContract",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "salt",
              type: "bytes32",
            },
            {
              internalType: "uint256[]",
              name: "extensions",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "nonces",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "v",
              type: "uint8",
            },
            {
              internalType: "bytes32",
              name: "r",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "permit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        approve: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        balanceOf: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        decimals: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        name: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        symbol: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        totalSupply: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        transfer: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        transferFrom: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        DOMAIN_SEPARATOR: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        eip712Domain: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        nonces: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        permit: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
    },
    YourContract: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
